export const SEED_USERS = [
  {
    username: 'admin',
    email: 'admin@dentaflow.ph',
    password: 'Password123!',
    name: 'Dr. Emily Watson, DDS',
    role: 'admin',
    title: 'Clinic Medical Director & Administrator',
    avatarUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150&auto=format&fit=crop&q=80',
  },
  {
    username: 'dr.thorne',
    email: 'thorne@dentaflow.ph',
    password: 'Password123!',
    name: 'Dr. Aris Thorne, DDS',
    role: 'dentist',
    title: 'Senior Restorative & Endodontic Specialist',
    avatarUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80',
  },
  {
    username: 'receptionist',
    email: 'reception@dentaflow.ph',
    password: 'Password123!',
    name: 'Maria Santos',
    role: 'receptionist',
    title: 'Front Desk & Patient Care Coordinator',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
  },
];

export const SEED_CHAIRS = [
  {
    id: 'chair-1',
    name: 'Operatory 1 (Hygiene & Preventive)',
    room: 'Suite 101 - East Wing',
    type: 'Hygiene',
    status: 'operational',
    equipment: ['Ultrasonic Scaler (EMS Piezon)', 'Air Polishing Unit', 'Intraoral Digital Camera'],
    notes: 'Dedicated for periodontal maintenance, prophylaxis, and fluoride therapy.',
  },
  {
    id: 'chair-2',
    name: 'Operatory 2 (Restorative & Endodontics)',
    room: 'Suite 102 - Central Operatory',
    type: 'Restorative',
    status: 'in_use',
    equipment: ['Rotary Endomotor (X-Smart Plus)', 'Apex Locator', 'LED Curing Unit (Valo)', 'Rubber Dam Kit'],
    notes: 'Equipped for RCT, composite aesthetic restorations, and crowns.',
  },
  {
    id: 'chair-3',
    name: 'Operatory 3 (Oral Surgery & Trauma)',
    room: 'Suite 103 - Sterile Surgical Suite',
    type: 'Surgical',
    status: 'operational',
    equipment: ['Surgical Piezotome', 'High-speed Surgical Handpiece 45°', 'Vital Signs Multi-parameter Monitor', 'Emergency Oxygen Kit'],
    notes: 'Sterile surgical environment for odontectomy, avulsions, lock jaw reduction, and implants.',
  },
  {
    id: 'chair-4',
    name: 'Operatory 4 (Orthodontics & Aesthetic)',
    room: 'Suite 104 - South Wing',
    type: 'Orthodontic',
    status: 'operational',
    equipment: ['Orthodontic Plier Set', 'Bracket Bonding Positioning Gauge', 'Intraoral 3D Scanner (iTero)'],
    notes: 'Used for wire adjustments, clear aligner attachments, and cosmetic consultations.',
  },
];

export const SEED_SHIFTS = [
  {
    id: 'shift-1',
    doctorName: 'Dr. Aris Thorne, DDS',
    role: 'Senior Dental Surgeon (Endodontics / Restorative)',
    licenseNumber: 'PRC-0084921',
    chairId: 'chair-2',
    chairName: 'Operatory 2 (Restorative & Endodontics)',
    timeIn: '08:00',
    timeOut: '17:00',
    daysOfWeek: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    status: 'active',
    contactPhone: '+63 917 555 0192',
  },
  {
    id: 'shift-2',
    doctorName: 'Dr. Elena Vance, DMD',
    role: 'Oral & Maxillofacial Surgeon',
    licenseNumber: 'PRC-0091244',
    chairId: 'chair-3',
    chairName: 'Operatory 3 (Oral Surgery & Trauma)',
    timeIn: '09:00',
    timeOut: '18:00',
    daysOfWeek: ['Tue', 'Thu', 'Sat'],
    status: 'active',
    contactPhone: '+63 918 555 8310',
  },
  {
    id: 'shift-3',
    doctorName: 'Lisa Ray, RDH',
    role: 'Registered Dental Hygienist',
    licenseNumber: 'PRC-0044810',
    chairId: 'chair-1',
    chairName: 'Operatory 1 (Hygiene & Preventive)',
    timeIn: '08:30',
    timeOut: '16:30',
    daysOfWeek: ['Mon', 'Tue', 'Wed', 'Fri', 'Sat'],
    status: 'active',
    contactPhone: '+63 920 555 3721',
  },
];

export const SEED_CONSUMABLES = [
  { id: 'cons-1', name: 'Lidocaine HCl 2% with Epinephrine 1:100,000', brand: 'Septodont (Xylocaine)', dosage: '1.8 mL', uom: 'carpule', pricePhp: 45, stockQuantity: 240, category: 'Anesthetics' },
  { id: 'cons-2', name: 'Articaine HCl 4% with Epinephrine 1:100,000', brand: 'Septodont (Septanest)', dosage: '1.7 mL', uom: 'carpule', pricePhp: 65, stockQuantity: 180, category: 'Anesthetics' },
  { id: 'cons-3', name: 'Mepivacaine 3% Plain (No Vasoconstrictor)', brand: 'Scandonest', dosage: '1.8 mL', uom: 'carpule', pricePhp: 55, stockQuantity: 90, category: 'Anesthetics' },
  { id: 'cons-4', name: 'Topical Benzocaine Gel 20%', brand: 'Sultan Healthcare', dosage: '30g jar', uom: 'unit', pricePhp: 750, stockQuantity: 8, category: 'Anesthetics' },
  { id: 'cons-5', name: 'Filtek Z350 XT Universal Restorative Composite', brand: '3M ESPE', dosage: '4g syringe', uom: 'syringe', pricePhp: 2100, stockQuantity: 35, category: 'Restoratives' },
  { id: 'cons-6', name: 'Single Bond Universal Adhesive', brand: '3M ESPE', dosage: '5 mL vial', uom: 'unit', pricePhp: 3800, stockQuantity: 12, category: 'Adhesives & Etch' },
  { id: 'cons-7', name: 'Phosphoric Acid Etchant Gel 37%', brand: 'Ultradent Ultra-Etch', dosage: '1.2 mL syringe', uom: 'syringe', pricePhp: 320, stockQuantity: 45, category: 'Adhesives & Etch' },
  { id: 'cons-8', name: 'Gutta-Percha Points 0.04 Taper Assorted (#20-#40)', brand: 'Dentsply Sirona', dosage: '60 points box', uom: 'box', pricePhp: 850, stockQuantity: 22, category: 'Endodontics' },
  { id: 'cons-9', name: 'AH Plus Bioceramic Root Canal Sealer', brand: 'Dentsply Sirona', dosage: '3g syringe', uom: 'unit', pricePhp: 4200, stockQuantity: 7, category: 'Endodontics' },
  { id: 'cons-10', name: 'Sodium Hypochlorite 5.25% Irrigant Solution', brand: 'Vista Dental', dosage: '500 mL bottle', uom: 'unit', pricePhp: 620, stockQuantity: 15, category: 'Endodontics' },
  { id: 'cons-11', name: 'Surgical Silk Suture 3-0 with Reverse Cutting Needle', brand: 'Ethicon', dosage: '12 sutures box', uom: 'box', pricePhp: 1850, stockQuantity: 18, category: 'Surgical' },
  { id: 'cons-12', name: 'Hemostatic Gelatin Sponge (Gelfoam)', brand: 'Pfizer', dosage: '10x10mm 50 cubes', uom: 'box', pricePhp: 1450, stockQuantity: 14, category: 'Surgical' },
  { id: 'cons-13', name: 'Prophy Paste Medium Grit Fluoride Mint', brand: 'Kerr Nupro', dosage: '340g jar', uom: 'unit', pricePhp: 1200, stockQuantity: 10, category: 'Preventive' },
];

export const SEED_DETERMINATIONS = [
  {
    id: 'det-surg-ext',
    treatmentName: 'Surgical Tooth Extraction (Complex / Impaction)',
    urgencyGroup: 'Emergency',
    urgencyRank: 1,
    minAmountPhp: 3500,
    maxAmountPhp: 9000,
    minDurationMinutes: 45,
    maxDurationMinutes: 90,
    commonlyUsedConsumables: [
      { consumableId: 'cons-1', consumableName: 'Lidocaine HCl 2%', defaultQuantity: 2, unitPricePhp: 45, brand: 'Septodont', standardDosage: '1.8 mL', uom: 'carpule' },
      { consumableId: 'cons-11', consumableName: 'Surgical Silk Suture 3-0', defaultQuantity: 1, unitPricePhp: 154, brand: 'Ethicon', standardDosage: '1 suture', uom: 'unit' },
      { consumableId: 'cons-12', consumableName: 'Hemostatic Gelatin Sponge', defaultQuantity: 1, unitPricePhp: 29, brand: 'Pfizer', standardDosage: '1 cube', uom: 'cube' },
    ],
    description: 'Surgical removal of non-restorable, impacted, or fractured roots requiring elevation and suturing.',
    indication: 'Non-restorable gross caries, severe periodontal involvement, or symptomatic impaction.',
  },
  {
    id: 'det-rct-molar',
    treatmentName: 'Molar Root Canal Therapy (Complete Biomechanical & Obturation)',
    urgencyGroup: 'LongProcedure',
    urgencyRank: 2,
    minAmountPhp: 8000,
    maxAmountPhp: 14000,
    minDurationMinutes: 60,
    maxDurationMinutes: 120,
    commonlyUsedConsumables: [
      { consumableId: 'cons-2', consumableName: 'Articaine HCl 4%', defaultQuantity: 2, unitPricePhp: 65, brand: 'Septodont', standardDosage: '1.7 mL', uom: 'carpule' },
      { consumableId: 'cons-8', consumableName: 'Gutta-Percha Points', defaultQuantity: 4, unitPricePhp: 14, brand: 'Dentsply', standardDosage: '4 points', uom: 'point' },
      { consumableId: 'cons-9', consumableName: 'AH Plus Bioceramic Sealer', defaultQuantity: 1, unitPricePhp: 150, brand: 'Dentsply', standardDosage: '0.1 mL', uom: 'application' },
      { consumableId: 'cons-10', consumableName: 'Sodium Hypochlorite 5.25%', defaultQuantity: 1, unitPricePhp: 50, brand: 'Vista Dental', standardDosage: '30 mL', uom: 'rinse' },
    ],
    description: 'Complete pulpectomy, instrumentation, disinfection, and three-dimensional warm gutta-percha obturation.',
    indication: 'Irreversible pulpitis, necrotic pulp with apical periodontitis in 3-4 rooted molar teeth.',
  },
  {
    id: 'det-composite-multi',
    treatmentName: 'Multi-Surface Aesthetic Composite Restoration',
    urgencyGroup: 'MaintenanceElective',
    urgencyRank: 3,
    minAmountPhp: 1800,
    maxAmountPhp: 3500,
    minDurationMinutes: 30,
    maxDurationMinutes: 60,
    commonlyUsedConsumables: [
      { consumableId: 'cons-1', consumableName: 'Lidocaine HCl 2%', defaultQuantity: 1, unitPricePhp: 45, brand: 'Septodont', standardDosage: '1.8 mL', uom: 'carpule' },
      { consumableId: 'cons-7', consumableName: 'Phosphoric Acid Etchant', defaultQuantity: 1, unitPricePhp: 30, brand: 'Ultradent', standardDosage: '0.2 mL', uom: 'application' },
      { consumableId: 'cons-6', consumableName: 'Single Bond Universal Adhesive', defaultQuantity: 1, unitPricePhp: 80, brand: '3M ESPE', standardDosage: '2 drops', uom: 'application' },
      { consumableId: 'cons-5', consumableName: 'Filtek Z350 XT Composite', defaultQuantity: 1, unitPricePhp: 250, brand: '3M ESPE', standardDosage: '0.5g', uom: 'application' },
    ],
    description: 'Conservative decay removal followed by total-etch bonding and layered nanohybrid composite placement.',
    indication: 'Class II, III, or IV carious lesions, defective margins, or fractured incisal angles.',
  },
  {
    id: 'det-prophylaxis-full',
    treatmentName: 'Full Mouth Ultrasonic Scaling & Air Polishing Prophylaxis',
    urgencyGroup: 'MaintenanceElective',
    urgencyRank: 3,
    minAmountPhp: 1500,
    maxAmountPhp: 2800,
    minDurationMinutes: 30,
    maxDurationMinutes: 45,
    commonlyUsedConsumables: [
      { consumableId: 'cons-13', consumableName: 'Prophy Paste Medium Grit Fluoride Mint', defaultQuantity: 1, unitPricePhp: 120, brand: 'Kerr', standardDosage: '1 cup', uom: 'cup' },
    ],
    description: 'Supragingival and subgingival plaque and calculus debridement using ultrasonic scaler followed by air-powder polishing.',
    indication: 'Routine semi-annual hygiene maintenance or localized marginal gingivitis.',
  },
];
